---
name: Build Pipeline

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: textbook/git-checkout-submodule-action@master
      - name: clusauth@docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: wearelumenai/clusauth/clusauth
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          dockerfile: build/Dockerfile
          tag_semver: true
          buildoptions: "--compress"
      - name: clusauth-vouch@docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: wearelumenai/clusauth/clusauth-vouch
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          dockerfile: build/Dockerfile.vouch
          tag_semver: true
          buildoptions: "--compress"
